[package]
name = "svn-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.0"
env_logger = "0.9.0"
log = "0.4.14"
tui = "0.17.0"
